Traceback (most recent call last):
  File "C:\Users\unerue\miniconda3\envs\vision\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\unerue\miniconda3\envs\vision\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\unerue\miniconda3\envs\vision\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\unerue\miniconda3\envs\vision\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\unerue\miniconda3\envs\vision\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\unerue\miniconda3\envs\vision\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\unerue\miniconda3\envs\vision\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\unerue\miniconda3\envs\vision\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from pulp import *

prob = LpProblem(name='0-1 Knapsack Problem', sense=LpMaximize)

x1 = LpVariable(name='x1', lowBound=0, cat='Binary')
x2 = LpVariable(name='x2', lowBound=0, cat='Binary')
x3 = LpVariable(name='x3', lowBound=0, cat='Binary')

prob += 7*x1 + 8*x2 + 3*x3

prob += 3*x1 + 4*x2 + 2*x3 <= 6

# Solving problem
prob.solve()
print('Status', LpStatus[prob.status])

print('Z = {}'.format(value(prob.objective)))
for i in prob.variables():
    print('{} = {}'.format(i.name, i.varValue))
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [1;32mIn [1][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpulp[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[0;32m      3[0m prob [38;5;241m=[39m LpProblem(name[38;5;241m=[39m[38;5;124m'[39m[38;5;124m0-1 Knapsack Problem[39m[38;5;124m'[39m, sense[38;5;241m=[39mLpMaximize)
[0;32m      5[0m x1 [38;5;241m=[39m LpVariable(name[38;5;241m=[39m[38;5;124m'[39m[38;5;124mx1[39m[38;5;124m'[39m, lowBound[38;5;241m=[39m[38;5;241m0[39m, cat[38;5;241m=[39m[38;5;124m'[39m[38;5;124mBinary[39m[38;5;124m'[39m)

[1;31mModuleNotFoundError[0m: No module named 'pulp'
ModuleNotFoundError: No module named 'pulp'

